version: "3.9"
services:


  gateway:
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
    env_file:
      - example.env
    container_name: gateway
    command: [ "/gateway/starter.sh" ]
    ports:
      - "8081:8080"
    restart: on-failure
    depends_on:
      - grpc_item
      - grpc_auth
    volumes:
      - ./gateway/:/gateway/
    networks:
      - net


  grpc_item:
    build:
      context: ./
      dockerfile: grpc_item/Dockerfile
    env_file:
      - example.env
    container_name: grpc_item
    ports:
      - "50051:50051"
    restart: on-failure
    volumes:
      - ./grpc_item/:/grpc_item/
    networks:
      - net

  grpc_auth:
    build:
      context: ./
      dockerfile: grpc_auth/Dockerfile
    env_file:
      - example.env
    container_name: grpc_auth
    ports:
      - "50052:50052"
    restart: on-failure
    volumes:
      - ./grpc_auth/:/grpc_auth/
    networks:
      - net


  grpc_heavy_duty:
    build:
      context: ./
      dockerfile: grpc_heavy_duty/Dockerfile
    env_file:
      - example.env
    container_name: grpc_heavy_duty
    ports:
      - "50053:50053"
    restart: on-failure
    volumes:
      - ./grpc_heavy_duty/:/grpc_heavy_duty/
    networks:
      - net


networks:
  net:
    driver: bridge
