# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/auth.proto\x12\x04\x61uth\"$\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"+\n\rLoginResponse\x12\x1a\n\x05token\x18\x01 \x01(\x0b\x32\x0b.auth.Token\"3\n\rSignupRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"Q\n\x15ValidateTokenResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.auth.User\x12\x1e\n\x07message\x18\x02 \x01(\x0b\x32\r.auth.Message2\xbd\x01\n\x0b\x41uthService\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12\x32\n\x06Signup\x12\x13.auth.SignupRequest\x1a\x13.auth.LoginResponse\x12H\n\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=27
  _globals['_USER']._serialized_end=63
  _globals['_TOKEN']._serialized_start=65
  _globals['_TOKEN']._serialized_end=87
  _globals['_MESSAGE']._serialized_start=89
  _globals['_MESSAGE']._serialized_end=115
  _globals['_LOGINREQUEST']._serialized_start=117
  _globals['_LOGINREQUEST']._serialized_end=167
  _globals['_LOGINRESPONSE']._serialized_start=169
  _globals['_LOGINRESPONSE']._serialized_end=212
  _globals['_SIGNUPREQUEST']._serialized_start=214
  _globals['_SIGNUPREQUEST']._serialized_end=265
  _globals['_VALIDATETOKENREQUEST']._serialized_start=267
  _globals['_VALIDATETOKENREQUEST']._serialized_end=304
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=306
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=387
  _globals['_AUTHSERVICE']._serialized_start=390
  _globals['_AUTHSERVICE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
