# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/heavy_duty.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/heavy_duty.proto\x12\nheavy_duty\"$\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\"2\n\x10HeavyDutyRequest\x12\x1e\n\x04user\x18\x01 \x01(\x0b\x32\x10.heavy_duty.User\"$\n\x11HeavyDutyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\\\n\x10HeavyDutyService\x12H\n\tHeavyDuty\x12\x1c.heavy_duty.HeavyDutyRequest\x1a\x1d.heavy_duty.HeavyDutyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.heavy_duty_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=39
  _globals['_USER']._serialized_end=75
  _globals['_HEAVYDUTYREQUEST']._serialized_start=77
  _globals['_HEAVYDUTYREQUEST']._serialized_end=127
  _globals['_HEAVYDUTYRESPONSE']._serialized_start=129
  _globals['_HEAVYDUTYRESPONSE']._serialized_end=165
  _globals['_HEAVYDUTYSERVICE']._serialized_start=167
  _globals['_HEAVYDUTYSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
