# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/item.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/item.proto\x12\x04item\"X\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tis_simple\x18\x03 \x01(\x08\x12\x12\n\nsample_int\x18\x04 \x01(\x05\x12\x0f\n\x07user_id\x18\x05 \x01(\x04\"Y\n\x11\x43reateItemRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tis_simple\x18\x02 \x01(\x08\x12\x12\n\nsample_int\x18\x03 \x01(\x05\x12\x0f\n\x07user_id\x18\x04 \x01(\x04\".\n\x12\x43reateItemResponse\x12\x18\n\x04item\x18\x01 \x01(\x0b\x32\n.item.Item\"#\n\x10ListItemsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\".\n\x11ListItemsResponse\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.item.Item\"-\n\x0eGetItemRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\"+\n\x0fGetItemResponse\x12\x18\n\x04item\x18\x01 \x01(\x0b\x32\n.item.Item\"e\n\x11UpdateItemRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tis_simple\x18\x03 \x01(\x08\x12\x12\n\nsample_int\x18\x04 \x01(\x05\x12\x0f\n\x07user_id\x18\x05 \x01(\x04\".\n\x12UpdateItemResponse\x12\x18\n\x04item\x18\x01 \x01(\x0b\x32\n.item.Item\"0\n\x11\x44\x65leteItemRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\"%\n\x12\x44\x65leteItemResponse\x12\x0f\n\x07success\x18\x01 \x01(\t2\xb1\x02\n\x0bItemService\x12;\n\x06\x43reate\x12\x17.item.CreateItemRequest\x1a\x18.item.CreateItemResponse\x12\x37\n\x04List\x12\x16.item.ListItemsRequest\x1a\x17.item.ListItemsResponse\x12\x32\n\x03Get\x12\x14.item.GetItemRequest\x1a\x15.item.GetItemResponse\x12;\n\x06Update\x12\x17.item.UpdateItemRequest\x1a\x18.item.UpdateItemResponse\x12;\n\x06\x44\x65lete\x12\x17.item.DeleteItemRequest\x1a\x18.item.DeleteItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=27
  _globals['_ITEM']._serialized_end=115
  _globals['_CREATEITEMREQUEST']._serialized_start=117
  _globals['_CREATEITEMREQUEST']._serialized_end=206
  _globals['_CREATEITEMRESPONSE']._serialized_start=208
  _globals['_CREATEITEMRESPONSE']._serialized_end=254
  _globals['_LISTITEMSREQUEST']._serialized_start=256
  _globals['_LISTITEMSREQUEST']._serialized_end=291
  _globals['_LISTITEMSRESPONSE']._serialized_start=293
  _globals['_LISTITEMSRESPONSE']._serialized_end=339
  _globals['_GETITEMREQUEST']._serialized_start=341
  _globals['_GETITEMREQUEST']._serialized_end=386
  _globals['_GETITEMRESPONSE']._serialized_start=388
  _globals['_GETITEMRESPONSE']._serialized_end=431
  _globals['_UPDATEITEMREQUEST']._serialized_start=433
  _globals['_UPDATEITEMREQUEST']._serialized_end=534
  _globals['_UPDATEITEMRESPONSE']._serialized_start=536
  _globals['_UPDATEITEMRESPONSE']._serialized_end=582
  _globals['_DELETEITEMREQUEST']._serialized_start=584
  _globals['_DELETEITEMREQUEST']._serialized_end=632
  _globals['_DELETEITEMRESPONSE']._serialized_start=634
  _globals['_DELETEITEMRESPONSE']._serialized_end=671
  _globals['_ITEMSERVICE']._serialized_start=674
  _globals['_ITEMSERVICE']._serialized_end=979
# @@protoc_insertion_point(module_scope)
